# ____  _                                        
#/ ___|| |_ _   _ _ __ _ __ ___   __ _ _ __  ___ 
#\___ \| __| | | | '__| '_ ` _ \ / _` | '_ \/ __|
# ___) | |_| |_| | |  | | | | | | (_| | | | \__ \
#|____/ \__|\__, |_|  |_| |_| |_|\__,_|_| |_|___/
#           |___/                                
#    _    _                 _ _   _         
#   / \  | | __ _  ___ _ __(_) |_| |_ _   _ 
#  / _ \ | |/ _` |/ __| '__| | __| __| | | |
# / ___ \| | (_| | (__| |  | | |_| |_| |_| |
#/_/   \_\_|\__,_|\___|_|  |_|\__|\__|\__, |
#                                     |___/ 
# https://github.com/styrman-g
# My alacritty configuration file. Feal free to take a copy and modify it.
#

[colors]
draw_bold_text_with_bright_colors = true

# Colors (Nordic)
[colors.primary]
background = '#242933'
foreground = '#BBBDAF'

[colors.normal]
black = '#191C1D'
red = '#BD6062'
green = '#A3D6A9'
yellow = '#F0DFAF'
blue = '#8FB4D8'
magenta = '#C7A9D9'
cyan = '#B6D7A8'
white = '#BDC5BD'

[colors.bright]
black = '#727C7C'
red = '#D18FAF'
green = '#B7CEB0'
yellow = '#BCBCBC'
blue = '#E0CF9F'
magenta = '#C7A9D9'
cyan = '#BBDA97'
white = '#BDC5BD'

[colors.selection]
text = '#000000'
background = '#F0DFAF'

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.8
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
